export interface HSCode {
  code: string;
  description: { en: string; ru: string; az: string };
}

export const HS_SECTIONS: HSCode[] = [
  { code: '01', description: { en: 'Live animals', ru: 'Живые животные', az: 'Canlı heyvanlar' } },
  { code: '02', description: { en: 'Meat and edible meat offal', ru: 'Мясо и пищевые мясные субпродукты', az: 'Ət və yeməli ət məhsulları' } },
  { code: '03', description: { en: 'Fish, crustaceans, molluscs', ru: 'Рыба и ракообразные', az: 'Balıq və xərçəngkimilər' } },
  { code: '04', description: { en: 'Dairy produce, eggs, honey', ru: 'Молочная продукция, яйца, мёд', az: 'Süd məhsulları, yumurta, bal' } },
  { code: '05', description: { en: 'Products of animal origin', ru: 'Продукты животного происхождения', az: 'Heyvan mənşəli məhsullar' } },
  { code: '06', description: { en: 'Live trees and plants', ru: 'Живые деревья и растения', az: 'Canlı ağaclar və bitkilər' } },
  { code: '07', description: { en: 'Edible vegetables', ru: 'Овощи', az: 'Yeməli tərəvəzlər' } },
  { code: '08', description: { en: 'Edible fruit and nuts', ru: 'Фрукты и орехи', az: 'Meyvələr və qoz-fındıq' } },
  { code: '09', description: { en: 'Coffee, tea, spices', ru: 'Кофе, чай, пряности', az: 'Qəhvə, çay, ədviyyatlar' } },
  { code: '10', description: { en: 'Cereals', ru: 'Зерновые', az: 'Taxıllar' } },
  { code: '15', description: { en: 'Fats and oils', ru: 'Жиры и масла', az: 'Yağlar' } },
  { code: '16', description: { en: 'Preparations of meat, fish', ru: 'Готовые мясные и рыбные продукты', az: 'Hazır ət və balıq məhsulları' } },
  { code: '17', description: { en: 'Sugars and sugar confectionery', ru: 'Сахар и кондитерские изделия', az: 'Şəkər və şirniyyat' } },
  { code: '20', description: { en: 'Preparations of vegetables, fruit', ru: 'Готовые овощные и фруктовые продукты', az: 'Hazır tərəvəz və meyvə məhsulları' } },
  { code: '22', description: { en: 'Beverages, spirits, vinegar', ru: 'Напитки, спиртные, уксус', az: 'İçkilər, spirtli içkilər, sirkə' } },
  { code: '24', description: { en: 'Tobacco', ru: 'Табак', az: 'Tütün' } },
  { code: '25', description: { en: 'Salt, sulphur, earth, stone', ru: 'Соль, сера, земля, камень', az: 'Duz, kükürd, torpaq, daş' } },
  { code: '27', description: { en: 'Mineral fuels, oils', ru: 'Минеральное топливо, нефть', az: 'Mineral yanacaqlar, neft' } },
  { code: '28', description: { en: 'Inorganic chemicals', ru: 'Неорганические химические вещества', az: 'Qeyri-üzvi kimyəvi maddələr' } },
  { code: '29', description: { en: 'Organic chemicals', ru: 'Органические химические вещества', az: 'Üzvi kimyəvi maddələr' } },
  { code: '30', description: { en: 'Pharmaceutical products', ru: 'Фармацевтическая продукция', az: 'Əczaçılıq məhsulları' } },
  { code: '31', description: { en: 'Fertilizers', ru: 'Удобрения', az: 'Gübrələr' } },
  { code: '33', description: { en: 'Essential oils, cosmetics', ru: 'Эфирные масла, косметика', az: 'Efir yağları, kosmetika' } },
  { code: '34', description: { en: 'Soap, waxes, candles', ru: 'Мыло, воск, свечи', az: 'Sabun, mum, şamlar' } },
  { code: '38', description: { en: 'Miscellaneous chemical products', ru: 'Различные химические продукты', az: 'Müxtəlif kimyəvi məhsullar' } },
  { code: '39', description: { en: 'Plastics', ru: 'Пластмассы', az: 'Plastik' } },
  { code: '40', description: { en: 'Rubber', ru: 'Резина', az: 'Rezin' } },
  { code: '41', description: { en: 'Raw hides and skins, leather', ru: 'Необработанные шкуры и кожа', az: 'Xam dəri və gön' } },
  { code: '44', description: { en: 'Wood and articles of wood', ru: 'Древесина', az: 'Ağac və ağac məmulatları' } },
  { code: '48', description: { en: 'Paper and paperboard', ru: 'Бумага и картон', az: 'Kağız və karton' } },
  { code: '49', description: { en: 'Printed books, newspapers', ru: 'Печатные книги, газеты', az: 'Çap kitabları, qəzetlər' } },
  { code: '50', description: { en: 'Silk', ru: 'Шёлк', az: 'İpək' } },
  { code: '52', description: { en: 'Cotton', ru: 'Хлопок', az: 'Pambıq' } },
  { code: '54', description: { en: 'Man-made filaments', ru: 'Искусственные нити', az: 'Süni lif' } },
  { code: '61', description: { en: 'Knitted or crocheted apparel', ru: 'Трикотажная одежда', az: 'Toxunma geyimlər' } },
  { code: '62', description: { en: 'Woven apparel', ru: 'Тканая одежда', az: 'Tikilmiş geyimlər' } },
  { code: '63', description: { en: 'Textile articles', ru: 'Текстильные изделия', az: 'Tekstil məmulatları' } },
  { code: '64', description: { en: 'Footwear', ru: 'Обувь', az: 'Ayaqqabı' } },
  { code: '69', description: { en: 'Ceramic products', ru: 'Керамические изделия', az: 'Keramika məmulatları' } },
  { code: '70', description: { en: 'Glass and glassware', ru: 'Стекло', az: 'Şüşə' } },
  { code: '71', description: { en: 'Precious stones, metals, jewellery', ru: 'Драгоценные камни, металлы', az: 'Qiymətli daşlar, metallar' } },
  { code: '72', description: { en: 'Iron and steel', ru: 'Чёрные металлы', az: 'Dəmir və polad' } },
  { code: '73', description: { en: 'Articles of iron or steel', ru: 'Изделия из чёрных металлов', az: 'Dəmir və polad məmulatları' } },
  { code: '74', description: { en: 'Copper', ru: 'Медь', az: 'Mis' } },
  { code: '76', description: { en: 'Aluminium', ru: 'Алюминий', az: 'Alüminium' } },
  { code: '82', description: { en: 'Tools, cutlery', ru: 'Инструменты, столовые приборы', az: 'Alətlər, bıçaq-çəngəl' } },
  { code: '83', description: { en: 'Miscellaneous articles of base metal', ru: 'Различные изделия из металлов', az: 'Metal məmulatları' } },
  { code: '84', description: { en: 'Machinery, mechanical appliances', ru: 'Машины и механическое оборудование', az: 'Maşınlar və mexaniki avadanlıqlar' } },
  { code: '85', description: { en: 'Electrical machinery and equipment', ru: 'Электрические машины и оборудование', az: 'Elektrik maşınları və avadanlıqları' } },
  { code: '86', description: { en: 'Railway locomotives, rolling stock', ru: 'Локомотивы и ж/д подвижной состав', az: 'Lokomotivlər, dəmir yolu nəqliyyatı' } },
  { code: '87', description: { en: 'Vehicles (not railway)', ru: 'Наземный транспорт (кроме ж/д)', az: 'Nəqliyyat vasitələri (dəmir yolu istisna)' } },
  { code: '88', description: { en: 'Aircraft, spacecraft', ru: 'Летательные аппараты', az: 'Təyyarələr, kosmik gəmilər' } },
  { code: '89', description: { en: 'Ships, boats', ru: 'Суда и лодки', az: 'Gəmilər və qayıqlar' } },
  { code: '90', description: { en: 'Optical, photographic, medical instruments', ru: 'Оптические, фото, медицинские приборы', az: 'Optik, foto, tibbi cihazlar' } },
  { code: '91', description: { en: 'Clocks and watches', ru: 'Часы', az: 'Saatlar' } },
  { code: '92', description: { en: 'Musical instruments', ru: 'Музыкальные инструменты', az: 'Musiqi alətləri' } },
  { code: '94', description: { en: 'Furniture, bedding, lighting', ru: 'Мебель, постельные принадлежности, освещение', az: 'Mebel, yataq ləvazimatları, işıqlandırma' } },
  { code: '95', description: { en: 'Toys, games, sports equipment', ru: 'Игрушки, игры, спортинвентарь', az: 'Oyuncaqlar, idman avadanlıqları' } },
  { code: '96', description: { en: 'Miscellaneous manufactured articles', ru: 'Различные готовые изделия', az: 'Müxtəlif hazır məmulatlar' } },
  { code: '97', description: { en: 'Works of art, antiques', ru: 'Произведения искусства, антиквариат', az: 'İncəsənət əsərləri, antikvar' } },
];
